name: Redzone Auto Deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Redzone Project
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Check branch name
        run: |
          echo "Branch name: ${{ github.ref }}"

      - name: Connect to server, Git pull, and Install Node.js Dependencies (Master)
        if: github.ref == 'refs/heads/master'
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{secrets.WORK_DIR_MASTER}} && git checkout master && git branch && git pull"
          npm install && npm run build

      - name: Connect to server, Git pull, and Install Node.js Dependencies (Develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{secrets.WORK_DIR_DEVELOP}} && git checkout develop && git branch && git pull"
          npm install && npm run build

      - name: Run server_deploy.sh script
        run: |
          './server_deploy.sh'
