name: Redzone Auto Deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Redzone Project
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Redzone Project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check branch name
        run: |
          echo "Branch name: ${{ github.ref }}"

      - name: Connect to server, Git pull (Master)
        if: github.ref == 'refs/heads/master'
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{secrets.WORK_DIR_MASTER}} && git branch && git pull && ./server_deploy.sh"

      - name: Connect to server, Git pull (Develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{secrets.WORK_DIR_DEVELOP}} && git branch && git pull && ./server_deploy.sh"
