name: Redzone Auto Deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Redzone Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Set WORK_DIR based on branch
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
            export WORK_DIR="${{ secrets.WORK_DIR_MASTER }}"
          elif [ "${GITHUB_REF}" == "refs/heads/develop" ]; then
            export WORK_DIR="${{ secrets.WORK_DIR_DEVELOP }}"
          else
            echo "Error: Unknown branch"
            exit 1
          fi
          echo "Deploying to ${WORK_DIR}"

      - name: Connect to server, Git pull and Install Node.js Dependencies
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${WORK_DIR} && git pull"
          npm install && npm run build
      - name: Run server_deploy.sh script
        run: |
          './server_deploy.sh'
